module.exports = Object.freeze({
  ACADIA (01): { parish: 'ACADIA (01)' },
  ALLEN (02): { parish: 'ALLEN (02)' },
  ASCENSION (03): { parish: 'ASCENSION (03)' },
  ASSUMPTION (04): { parish: 'ASSUMPTION (04)' },
  AVOYELLES (05): { parish: 'AVOYELLES (05)' },
  BEAUREGARD (06): { parish: 'BEAUREGARD (06)' },
  BIENVILLE (07): { parish: 'BIENVILLE (07)' },
  BOSSIER (08): { parish: 'BOSSIER (08)' },
  CADDO (09): { parish: 'CADDO (09)' },
  CALCASIEU (10): { parish: 'CALCASIEU (10)' },
  CALDWELL (11): { parish: 'CALDWELL (11)' },
  CAMERON (12): { parish: 'CAMERON (12)' },
  CATAHOULA (13): { parish: 'CATAHOULA (13)' },
  CLAIBORNE (14): { parish: 'CLAIBORNE (14)' },
  CONCORDIA (15): { parish: 'CONCORDIA (15)' },
  DE SOTO (16): { parish: 'DE SOTO (16)' },
  EAST BATON ROUGE (17): { parish: 'EAST BATON ROUGE (17)' },
  EAST CARROLL (18): { parish: 'EAST CARROLL (18)' },
  EAST FELICIANA (19): { parish: 'EAST FELICIANA (19)' },
  EVANGELINE (20): { parish: 'EVANGELINE (20)' },
  FRANKLIN (21): { parish: 'FRANKLIN (21)' },
  GRANT (22): { parish: 'GRANT (22)' },
  IBERIA (23): { parish: 'IBERIA (23)' },
  IBERVILLE (24): { parish: 'IBERVILLE (24)' },
  JACKSON (25): { parish: 'JACKSON (25)' },
  JEFFERSON (26): { parish: 'JEFFERSON (26)' },
  JEFFERSON DAVIS (27): { parish: 'JEFFERSON DAVIS (27)' },
  LAFAYETTE (28): { parish: 'LAFAYETTE (28)' },
  LAFOURCHE (29): { parish: 'LAFOURCHE (29)' },
  LASALLE (30): { parish: 'LASALLE (30)' },
  LINCOLN (31): { parish: 'LINCOLN (31)' },
  LIVINGSTON (32): { parish: 'LIVINGSTON (32)' },
  MADISON (33): { parish: 'MADISON (33)' },
  MOREHOUSE (34): { parish: 'MOREHOUSE (34)' },
  NATCHITOCHES (35): { parish: 'NATCHITOCHES (35)' },
  ORLEANS (36): { parish: 'ORLEANS (36)' },
  OUACHITA (37): { parish: 'OUACHITA (37)' },
  PLAQUEMINES (38): { parish: 'PLAQUEMINES (38)' },
  POINTE COUPEE (39): { parish: 'POINTE COUPEE (39)' },
  RAPIDES (40): { parish: 'RAPIDES (40)' },
  RED RIVER (41): { parish: 'RED RIVER (41)' },
  RICHLAND (42): { parish: 'RICHLAND (42)' },
  SABINE (43): { parish: 'SABINE (43)' },
  ST. BERNARD (44): { parish: 'ST. BERNARD (44)' },
  ST. CHARLES (45): { parish: 'ST. CHARLES (45)' },
  ST. HELENA (46): { parish: 'ST. HELENA (46)' },
  ST. JAMES (47): { parish: 'ST. JAMES (47)' },
  ST. JOHN THE BAPTIST (48): { parish: 'ST. JOHN THE BAPTIST (48)' },
  ST. LANDRY (49): { parish: 'ST. LANDRY (49)' },
  ST. MARTIN (50): { parish: 'ST. MARTIN (50)' },
  ST. MARY (51): { parish: 'ST. MARY (51)' },
  ST. TAMMANY (52): { parish: 'ST. TAMMANY (52)' },
  TANGIPAHOA (53): { parish: 'TANGIPAHOA (53)' },
  TENSAS (54): { parish: 'TENSAS (54)' },
  TERREBONNE (55): { parish: 'TERREBONNE (55)' },
  UNION (56): { parish: 'UNION (56)' },
  VERMILION (57): { parish: 'VERMILION (57)' },
  VERNON (58): { parish: 'VERNON (58)' },
  WASHINGTON (59): { parish: 'WASHINGTON (59)' },
  WEBSTER (60): { parish: 'WEBSTER (60)' },
  WEST BATON ROUGE (61): { parish: 'WEST BATON ROUGE (61)' },
  WEST CARROLL (62): { parish: 'WEST CARROLL (62)' },
  WEST FELICIANA (63): { parish: 'WEST FELICIANA (63)' },
  WINN (64): { parish: 'WINN (64)' },
});
